train: 0
log_dir: logs/clutter
model_name: test_fold13_lr1e-4_mean_only
pretrained: 0

dataset_dir: datasets/mask-net-real
fold_num: 10
train_size: 0
val_size: 0
test_size: 6000
label_type: modal
target_type: amodal

model_type: siamese-u-net
epochs: 20
lr: 0.0001
feature_maps: 24
reg_factor: 0
dropout: 0.1
batch_size: 32
eval_size: 640

real_im_path: datasets/mask-net-real/fold_0010
vis: 0
